<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [   
	'Login' => 'Авторизация', 
	'Password' => 'Пароль', 
	'Username' => 'Имя пользователя',
	'Remember Me' => 'Запомнить меня',
	'Create' => 'Создать',
	'Creation' => 'Создание',
	'Delete' => 'Удалить',
	'Save' => 'Сохранить',
	'Edit' => 'Редактировать',
	'edit' => 'редактирование',
	'Editing' => 'Редактирование',
	'Update' => 'Обновить',
	'Done' => 'Выполнено',
	'Enter to system' => 'Войдите в систему',
	'Apply' => 'Применить',

	'Code' => 'Код',
	'Name' => 'Название',
	'Cnt' => 'К-во',
	'Model' => 'Модель',

	'Catalog' => 'Справочник',
	'Short Name' => 'Краткое название',
	'Create Catalog' => 'Создать спр.',
	'Plants' => 'Заводы',
	'Ships' => 'Корабли',
	'Kved' => 'Коды УКВЕД',
	'Color' => 'Цвета',
	'Salon colors' => 'Цвета салона',
	'Cat Models' => 'Модели',
	'Create Cat Model' => 'Создать модель',
	'Model name' => 'Название сокр.',
	'Model full name' => 'Название полн.',
	'Cars' => 'Автомобили',
	'Create Car' => 'Создать авт.',
	'Model ID' => 'Модель',
	'Color ID' => 'Цвет',
	'Color Sal ID' => 'Цвет салона',
	'Enj Num' => '№ двиг.',
	'Stocks' => 'Склады',
	'Dillers' => 'Диллеры',
	'Stock' => 'Склад',
	'Diller' => 'Диллер',
	'Load manifest' => 'Загрузка манифестов',
	'Load packing' => 'Загрузка пакингов',
	'file' => 'Файл',
	'Load' => 'Загрузить',

	'Cars on road' => 'Авто в дороге',
	'Cars on custum' => 'Авто на таможне',
	'Cars on distr' => 'Авто в дистриб.',
	'Select a model' => 'Укажите модель',
	'Select a color' => 'Укажите цвет',
	'Custum Date' => 'Дата растаможки',
	'Custum code' => '№ декларации',
	'Select diller' => 'Укажите диллера',
	'Select stock' => 'Укажите склад',
	
	'Reports' => 'Отчеты',
	'Custum custum_num' => '№ декларации',

];
